version: '3'
 
services:
  rabbitmq:
    container_name: rabbitmq
    image: "rabbitmq:3-management"
    hostname: "rabbit"
    restart: always
    ports:
     - "15672:15672"
      - "5672:5672"
    networks:
     - web
    labels:
      NAME: "rabbitmq"
    volumes:
    - ./rabbitmq-isolated.conf:/etc/rabbitmq/rabbitmq.config
 
networks:
    web:
      external: true
      name: web
